{
  GPU: {
    use_gpu: True,             #是否使用GPU，True表示使用
    device_id: [0],            #所使用的GPU设备号，type=list
  },

  CONFIG: {
      dataset_name: 'Rml2016_10a',     # 所选择的数据集的名称
      model_name: 'VTCNN2',       # 攻击模型的名称
      criterion_name: 'CrossEntropyLoss',       # 失函数的名称
      optimizer_name: 'Adam',     # 优化器的名称（torch.nn中）
      metrics: ['accuracy'],        # 评价标准的名称（metric文件夹中）
      adjust_lr: True,               # 是否自动的变化学习率
      load_model: False,              # 是否加载预训练模型（测试、迁移）
      defender_name: 'FGSM_Adv_Trainer'
  },

  ARG: {
      epoch: 1200,         # 训练epoch
      batch_size: 128,    # 训练集batch_size
  },

  VTCNN2: {
      output_dim: 11,
  },

  Adam: {
      lr: 0.001,                  # 学习率
      weight_decay: 1.0e-3,        # 权重衰减
  },

  Rml2016_10a: {
      dirname: "/home/yuzhen/wireless/RML2016.10a",  # 数据集文件路径
      prop: 0.5,                     # 所占的比例
  },

  LrAdjust: {
      lr_step: 10,                   # 学习率变化的间隔
      lr_decay: 0.5,                 # 学习率变化的幅度
      increase_bottom: 5,            # 退火前学习率增加的上界
      increase_amp: 1.1,             # 学习率增加的幅度
      warm_lr: 0.0005,               # 当学习率小于1e-8时，恢复学习率为warm_lr
  },

  LoadModel: {
      filename: '/home/yuzhen/wireless/model/VTCNN2/VTCNN2_Epoch85.pkl',     #加载模型的位置，与上面模型要对应
      base_epoch: 0,           # 预训练的基础epoch
  },

  FGSM_Adv_Trainer: {
      clean_sigma: 0.5,
      adv_sigma: 0.5,
      alp_coef: 0.5
  }
}