sh scripts/attack/fgsm_transfer/black_attack/with_vtcnn2_attack.sh
sh scripts/attack/fgsm_transfer/black_attack/with_based_vgg_attack.sh
sh scripts/attack/fgsm_transfer/black_attack/with_based_resnet_attack.sh
sh scripts/attack/fgsm_transfer/black_attack/with_based_gru_attack.sh
sh scripts/attack/fgsm_transfer/black_attack/with_based_lstm_attack.sh
sh scripts/attack/fgsm_transfer/black_attack/with_cldnn_attack.sh